name: RunIn_SemiSuperv
channels:
  - conda-forge
  - defaults
dependencies:
  - imbalanced-learn=0.13.0
  - matplotlib=3.10.3
  - numpy=2.3.1
  - pandas=2.3.0
  - optuna=4.4.0
  - optuna-dashboard=0.19.0
  - pip=25.1
  - psycopg2-binary=2.9.10
  - pytest=8.4.1
  - python=3.13.0
  - scikit-learn=1.6.1
  - scipy=1.16.0
  - tqdm=4.67.1

  - pip:
      - git+https://github.com/ThalerG/delayedsw
